# Generated by Django 4.2 on 2023-04-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_category_delete_storycategory'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryCategory',
            new_name='Category',
        ),
    ]
