# Generated by Django 4.2 on 2023-04-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_rename_category_story_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='category_id',
            new_name='category',
        ),
    ]
