# Generated by Django 4.2 on 2023-04-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_rename_category_id_story_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
