# Generated by Django 4.2 on 2023-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_alter_storyview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
