# Generated by Django 4.2 on 2023-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_alter_story_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.CharField(max_length=5000),
        ),
    ]
