# Generated by Django 4.2 on 2023-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0020_storyquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyview',
            name='story_owner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
